apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "tanzu-observability-demo.fullname" .  }}
    service: notification
    shard: blue
  name: notification-blue
  namespace: {{ .Values.namespace   }}
spec:
  replicas: {{ .Values.replicaCount.blue  }}
  selector:
    matchLabels:
      app: {{ include "tanzu-observability-demo.fullname" .  }}
      service: notification
      shard: blue
  template:
    metadata:
      labels:
        app: {{ include "tanzu-observability-demo.fullname" .  }}
        service: notification
        shard: blue
    spec:
      containers:
      - name: notification
        image: {{ .Values.image.repository }}/notification:latest
        imagePullPolicy: Always 
        command:
        - "java"
        - "-jar"
        - "/notification.jar"
        - "--spring.config.location=/conf/notification-app.yml"
        ports:
        - containerPort: 50056
          name: application
          protocol: TCP
        volumeMounts:
        - name: conf
          mountPath: /conf
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 350Mi
      volumes:
      - name: conf
        configMap:
          name: app-config-blue
          defaultMode: 0744
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "tanzu-observability-demo.fullname" .  }}
    service: notification
    shard: green
  name: notification-green
  namespace: {{ .Values.namespace   }}
spec:
  replicas: {{ .Values.replicaCount.green  }}
  selector:
    matchLabels:
      app: {{ include "tanzu-observability-demo.fullname" .  }}
      service: notification
      shard: green
  template:
    metadata:
      labels:
        app: {{ include "tanzu-observability-demo.fullname" .  }}
        service: notification
        shard: green
    spec:
      containers:
        - name: notification
          image: {{ .Values.image.repository }}/notification:latest
          imagePullPolicy: Always
          command:
            - "java"
            - "-jar"
            - "/notification.jar"
            - "--spring.config.location=/conf/notification-app.yml"
          ports:
            - containerPort: 50056
              name: application
              protocol: TCP
          volumeMounts:
            - name: conf
              mountPath: /conf
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 350Mi
      volumes:
        - name: conf
          configMap:
            name: app-config-green
            defaultMode: 0744
---
apiVersion: v1
kind: Service
metadata:
  name: notification
  namespace: {{ .Values.namespace   }}
spec: 
  selector:
    app: {{ include "tanzu-observability-demo.fullname" .  }}
    service: notification  
  type: ClusterIP
  ports:
  - name: application
    port: 50056

