---
apiVersion: v1
kind: Service
metadata:
  name: shopping
  namespace: $K8S_NAMESPACE
spec: 
  selector:
    app: $K8S_APPLICATION
    service: shopping
  type: LoadBalancer
  ports:
  - name: application
    port: 50050
  - name: admin
    port: 50150
